Update k8s-deploy-on-trigger.yml

diff --git a/.github/workflows/k8s-deploy-on-trigger.yml b/.github/workflows/k8s-deploy-on-trigger.yml
--- a/.github/workflows/k8s-deploy-on-trigger.yml
+++ b/.github/workflows/k8s-deploy-on-trigger.yml
@@ -23,7 +23,10 @@ on:
 
 env:
   REGISTRY: ghcr.io
-  Overlay: ${{ inputs.BranchName == 'develop' && 'acc' || inputs.BranchName == 'main' && 'prd' || inputs.BranchName }}
+  BRANCH_NAME: ${{ inputs.BranchName || github.event.client_payload.BranchName }}
+  IMAGE_NAME:  ${{ inputs.DockerImageName || github.event.client_payload.DockerImageName }}
+  RELEASE_TAG: ${{ inputs.ReleaseTag || github.event.client_payload.ReleaseTag }}
+  Overlay: ${{ env.BRANCH_NAME == 'develop' && 'acc' || env.BRANCH_NAME == 'main' && 'prd' }}
 
 permissions:
   contents: write  # needed to push commits
@@ -37,12 +40,30 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       files: ${{ steps.find.outputs.files }}
-    steps:
+    steps:    
+      - name: Validate inputs
+        run: |
+          if [ -z "${{ env.BRANCH_NAME }}" ]; then
+            echo "BRANCH_NAME is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ env.IMAGE_NAME }}" ]; then
+            echo "IMAGE_NAME is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ env.RELEASE_TAG }}" ]; then
+            echo "RELEASE_TAG is missing"
+            exit 1
+          fi
+          echo "Inputs are valid: BRANCH_NAME=${{ env.BRANCH_NAME }}, IMAGE_NAME=${{ env.IMAGE_NAME }}, RELEASE_TAG=${{ env.RELEASE_TAG }}"
+
       - uses: actions/checkout@v6
       - id: find
         shell: bash
         run: |
-          MATCHES=$(git grep -l -F --no-index "${{ inputs.DockerImageName }}:" -- "deployments/dlz/**/${{ env.Overlay }}/patch-deployment.yaml" || true)
+          MATCHES=$(git grep -l -F --no-index "${{ env.IMAGE_NAME }}:" -- "deployments/dlz/**/${{ env.Overlay }}/patch-deployment.yaml" || true)
           FILES=$(printf "%s\n" "$MATCHES" | jq -R -s -c 'split("\n")[:-1]')
           echo "files=$FILES" >> $GITHUB_OUTPUT
 
@@ -59,8 +80,8 @@ jobs:
 
             gh workflow run k8s-deploy-connector.yml \
             -f FilePath="$file" \
-            -f DockerImageName="${{ inputs.DockerImageName }}" \
-            -f ReleaseTag="${{ inputs.ReleaseTag }}" \
+            -f DockerImageName="${{ env.IMAGE_NAME }}" \
+            -f ReleaseTag="${{ env.RELEASE_TAG }}" \
             -f Environment="tce-dip-${{ env.Overlay }}"
             
             echo "Fetching latest run..."
